
DROP TABLE IF EXISTS `DummyData`.`STUDENT`;
CREATE TABLE  `DummyData`.`STUDENT` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `SNAME` varchar(20) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `DummyData`.`MARKS`;
CREATE TABLE  `DummyData`.`MARKS` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `SID` int(11) DEFAULT NULL,
  `S1` int(11) DEFAULT NULL,
  `S2` int(11) DEFAULT NULL,
  `S3` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `par_ind` (`SID`),
  CONSTRAINT `fk_student` FOREIGN KEY (`SID`) REFERENCES `STUDENT` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=latin1;
